version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
  create_infrastructure: 
        docker:
          - image: amazon/aws-cli
        steps:
          - checkout
          - run:
              name: Create Cloudformation Stack
              command: |
                aws cloudformation deploy \
                  --template-file cloudFormation/template.yml \
                  --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                  --region us-east-1  
  ansible_playbook:
        docker:
          - image: ubuntu
            environment:
              TZ: "America/Los_Angeles"
        steps:
          - checkout
          - add_ssh_keys:
              fingerprints: [16:1e:28:18:89:a9:13:3b:8b:05:ea:9b:e4:ac:ac:16]  
          - run:
              name: Install Dependencies
              command: |
                apt update -y
                apt install awscli -y
                apt install python3-pip -y
                apt install ansible -y
          - run:
              name: Configure Server
              command: |
                aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --output text >> ansible/inventory.txt
                ansible-playbook -i ansible/inventory.txt ansible/main.yml

# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      - create_infrastructure
      - ansible_playbook:
          requires:
            - create_infrastructure